name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install base dependencies
        run: npm ci
      - name: Save original package.json
        run: cp package.json package.json.original

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Restore original package.json
        run: mv package.json.original package.json
      - name: Build
        run: npm run build

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Restore original package.json
        run: mv package.json.original package.json
      - name: Run Lint
        run: npm run lint
        continue-on-error: true

  test:
    needs: setup
    strategy:
      matrix:
        ts-version: ["~5.x", "~4.x", "~3.x"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Change TypeScript version
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "${{ matrix.ts-version }}"/' package.json
          npm install --no-save --force  # Ключевое изменение!
      - name: Run Tests
        run: npm test
      - name: Restore original package.json
        if: always()
        run: mv package.json.original package.json
