name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  testV5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV4:
    needs: testV5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Change dependency
        run: |
          sed -i 's/"typescript": "\~[0-9]\+\.[0-9]\+\.[0-9]\+"/"typescript": "~4.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV3:
    needs: testV4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Change dependency
        run: |
          sed -i 's/"typescript": "\~4.x"/"typescript": "~3.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
