name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

  testV6Node24:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  testV6Node22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  testV6Node20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  testV5Node24:
    needs: testV6Node24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~5.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV5Node22:
    needs: testV6Node22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~5.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV5Node20:
    needs: testV6Node20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~5.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV4Node24:
    needs: testV5Node24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~4.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV4Node22:
    needs: testV5Node22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~4.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV4Node20:
    needs: testV5Node20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~4.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV3Node24:
    needs: testV4Node24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~3.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV3Node22:
    needs: testV4Node22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~3.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  testV3Node20:
    needs: testV4Node20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Change dependency
        run: |
          sed -i 's/"typescript": ".*"/"typescript": "~3.x"/' package.json
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
